name: Protect main branch pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  MAIN_frontend:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: 'frontend'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (npm install)
        run: npm install
      - name: Check style (lint)
        run: npm run eslint
      - name: build
        run: npm run build
  MAIN_backend:
    needs: [MAIN_frontend]
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: 'backend'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (npm install)
        run: npm install
      - name: Check style (lint)
        run: npm run eslint
